export const FETCH_ARTWORKS_REQUEST = 'FETCH_ARTWORKS_REQUEST';
export const FETCH_ARTWORKS_SUCCESS = 'FETCH_ARTWORKS_SUCCESS';
export const FETCH_ARTWORKS_FAILURE = 'FETCH_ARTWORKS_FAILURE';
export const FETCH_MORE_ARTWORKS_REQUEST = 'FETCH_MORE_ARTWORKS_REQUEST';
export const FETCH_MORE_ARTWORKS_SUCCESS = 'FETCH_MORE_ARTWORKS_SUCCESS';
export const FETCH_MORE_ARTWORKS_FAILURE = 'FETCH_MORE_ARTWORKS_FAILURE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_QUERY = 'SET_QUERY';

export const FETCH_FAVOURITES_REQUEST = 'favourites/FETCH_FAVOURITES_REQUEST';
export const FETCH_FAVOURITES_SUCCESS = 'favourites/FETCH_FAVOURITES_SUCCESS';
export const FETCH_FAVOURITES_FAILURE = 'favourites/FETCH_FAVOURITES_FAILURE';
export const ADD_FAVORITE = 'favourites/ADD_FAVORITE';
export const REMOVE_FAVORITE = 'favourites/REMOVE_FAVORITE';
